# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  gallery: 
    jobs:
      build:
        docker:
          - image: circleci/node
          - image: circleci/mysql
            environment: 
              MYSQL_USER: student
              MYSQL_DATABASE: gallery
        steps:
          - checkout
          - run: npm run reset-db
          - run: npm run seed-db
      test:
        steps:
          - run: npm run test

workflows:
  main:
    jobs:
      - gallery/build
      - gallery/test