version: 2.1
description: Orb for Etsy gallery component clone project

jobs:
  test:
    docker:
      - image: circleci/node
      - image: circleci/mysql
        environment: 
          MYSQL_USER: student
          MYSQL_PASSWORD: student
          MYSQL_DATABASE: gallery
    steps:
      - checkout
      - run: 
          name: Install MySQL, start server, install dependencies, seedDB and run tests
          command: |
            sudo apt-get install default-mysql-client
            mysql.server start
            npm install
            npm run reset-db
            npm run test
      

